<a href="https://colab.research.google.com/github/gulabpatel/AutoML/blob/main/12%3A%20FLAML_Class_Reg_TimeSeries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## FLAML: A Fast and Lightweight AutoML Library

In [ ]:
!pip install flaml

# Classification Problem

In [2]:
from flaml import AutoML
from sklearn.datasets import load_iris
# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 100,  # in seconds
    "metric": 'accuracy',
    "task": 'classification',
    "log_file_name": "iris.log",
}
X_train, y_train = load_iris(return_X_y=True)
# Train with labeled input data
automl.fit(X_train=X_train, y_train=y_train,
           **automl_settings)

[flaml.automl: 10-02 10:38:47] {1432} INFO - Evaluation method: cv
[flaml.automl: 10-02 10:38:47] {1478} INFO - Minimizing error metric: 1-accuracy
[flaml.automl: 10-02 10:38:47] {1515} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'catboost', 'xgboost', 'extra_tree', 'lrl1']
[flaml.automl: 10-02 10:38:47] {1748} INFO - iteration 0, current learner lgbm
[flaml.automl: 10-02 10:38:47] {1866} INFO - Estimated sufficient time budget=428s. Estimated necessary time budget=8s.
[flaml.automl: 10-02 10:38:47] {1944} INFO -  at 0.1s,	estimator lgbm's best error=0.0733,	best estimator lgbm's best error=0.0733
[flaml.automl: 10-02 10:38:47] {1748} INFO - iteration 1, current learner lgbm
[flaml.automl: 10-02 10:38:47] {1944} INFO -  at 0.1s,	estimator lgbm's best error=0.0733,	best estimator lgbm's best error=0.0733
[flaml.automl: 10-02 10:38:47] {1748} INFO - iteration 2, current learner lgbm
[flaml.automl: 10-02 10:38:47] {1944} INFO -  at 0.2s,	estimator lgbm's best error=0.0533,	be

In [3]:
# Predict
print(automl.predict_proba(X_train))
# Export the best model
print(automl.model)

[[9.80483031e-01 1.95166436e-02 3.25820402e-07]
 [9.47464579e-01 5.25334752e-02 1.94577368e-06]
 [9.71402187e-01 2.85968930e-02 9.19799977e-07]
 [9.46285943e-01 5.37104282e-02 3.62834019e-06]
 [9.84023449e-01 1.59762700e-02 2.81071461e-07]
 [9.83055447e-01 1.69441412e-02 4.12157653e-07]
 [9.76064339e-01 2.39344615e-02 1.19945266e-06]
 [9.70281426e-01 2.97177590e-02 8.14790506e-07]
 [9.36056940e-01 6.39374898e-02 5.57011601e-06]
 [9.46409549e-01 5.35886492e-02 1.80168146e-06]
 [9.83741286e-01 1.62585328e-02 1.80922164e-07]
 [9.62981807e-01 3.70164363e-02 1.75650537e-06]
 [9.47424899e-01 5.25733259e-02 1.77497095e-06]
 [9.72460526e-01 2.75385265e-02 9.47173391e-07]
 [9.95487370e-01 4.51262067e-03 9.74463388e-09]
 [9.96077569e-01 3.92240806e-03 2.26034078e-08]
 [9.93056685e-01 6.94325207e-03 6.31443381e-08]
 [9.80482942e-01 1.95166418e-02 4.15826420e-07]
 [9.79337642e-01 2.06620820e-02 2.76127039e-07]
 [9.86677541e-01 1.33221896e-02 2.69832951e-07]
 [9.54256400e-01 4.57424801e-02 1.119881

# Regression Problem

In [4]:
## Regression Problem
from flaml import AutoML
from sklearn.datasets import load_boston
# Initialize an AutoML instance
automl = AutoML()
# Specify automl goal and constraint
automl_settings = {
    "time_budget": 100,  # in seconds
    "metric": 'r2',
    "task": 'regression',
    "log_file_name": "boston.log",
}
X_train, y_train = load_boston(return_X_y=True)
# Train with labeled input data
automl.fit(X_train=X_train, y_train=y_train,
           **automl_settings)
# Predict
print(automl.predict(X_train))
# Export the best model
print(automl.model)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this case special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset 

[25.85426879 22.17737651 33.79509964 33.47189557 35.61127167 26.6926382
 21.53656446 20.99173684 16.18673463 18.75433976 18.20961633 20.48286627
 20.20745331 19.5131759  18.82401423 19.81864373 21.91420674 17.53721008
 18.69698259 19.07769813 14.3021372  18.32367106 16.63348583 15.34809335
 16.27978499 15.13176242 16.94561436 15.20221211 18.67737191 20.75076542
 13.88486622 17.70376242 13.89318927 14.90744983 14.32837615 21.02020963
 20.89410764 21.52937191 23.19568492 30.3824402  34.45306735 29.43834549
 24.62262048 24.62262048 22.21884844 20.87353145 20.36481607 18.09945043
 15.55273032 18.67322033 20.4058421  21.53510487 24.1301244  21.73345138
 17.74586736 34.48285914 23.17178682 31.55632404 23.26235097 20.39233374
 18.98627393 17.89811291 22.71262836 25.23349363 32.76974079 25.04432847
 19.83367435 20.94710592 19.92700235 21.23614492 23.62275307 21.08771163
 22.31713619 23.46816704 24.39319272 22.93449232 21.05889974 21.25605159
 21.17094097 21.4104049  26.32531539 24.84165632 23.

In [5]:
# Predict
print(automl.predict(X_train))
# Export the best model
print(automl.model)

[25.85426879 22.17737651 33.79509964 33.47189557 35.61127167 26.6926382
 21.53656446 20.99173684 16.18673463 18.75433976 18.20961633 20.48286627
 20.20745331 19.5131759  18.82401423 19.81864373 21.91420674 17.53721008
 18.69698259 19.07769813 14.3021372  18.32367106 16.63348583 15.34809335
 16.27978499 15.13176242 16.94561436 15.20221211 18.67737191 20.75076542
 13.88486622 17.70376242 13.89318927 14.90744983 14.32837615 21.02020963
 20.89410764 21.52937191 23.19568492 30.3824402  34.45306735 29.43834549
 24.62262048 24.62262048 22.21884844 20.87353145 20.36481607 18.09945043
 15.55273032 18.67322033 20.4058421  21.53510487 24.1301244  21.73345138
 17.74586736 34.48285914 23.17178682 31.55632404 23.26235097 20.39233374
 18.98627393 17.89811291 22.71262836 25.23349363 32.76974079 25.04432847
 19.83367435 20.94710592 19.92700235 21.23614492 23.62275307 21.08771163
 22.31713619 23.46816704 24.39319272 22.93449232 21.05889974 21.25605159
 21.17094097 21.4104049  26.32531539 24.84165632 23.

# Time Series Problem

In [ ]:
pip install flaml[forecast]

In [7]:
import numpy as np
from flaml import AutoML
X_train = np.arange('2014-01', '2021-01', dtype='datetime64[M]')
y_train = np.random.random(size=72)
automl = AutoML()
automl.fit(X_train=X_train[:72],  # a single column of timestamp
           y_train=y_train,  # value for each timestamp
           period=12,  # time horizon to forecast, e.g., 12 months
           task='forecast', time_budget=100,  # time budget in seconds
           log_file_name="forecast.log",
          )
print(automl.predict(X_train[72:]))

[flaml.automl: 10-02 10:54:21] {1432} INFO - Evaluation method: cv
[flaml.automl: 10-02 10:54:21] {1478} INFO - Minimizing error metric: mape
[flaml.automl: 10-02 10:54:21] {1515} INFO - List of ML learners in AutoML Run: ['prophet', 'arima', 'sarimax']
[flaml.automl: 10-02 10:54:21] {1748} INFO - iteration 0, current learner prophet
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:prophet:n_changepoints greater than number of observations. Using 8.
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True 

2020-01-01    0.705688
2020-02-01    0.705688
2020-03-01    0.705688
2020-04-01    0.705688
2020-05-01    0.705688
2020-06-01    0.705688
2020-07-01    0.705688
2020-08-01    0.705688
2020-09-01    0.705688
2020-10-01    0.705688
2020-11-01    0.705688
2020-12-01    0.705688
Freq: MS, Name: predicted_mean, dtype: float64


In [8]:
# Export the best model
print(automl.model)