<a href="https://colab.research.google.com/github/gulabpatel/ML_Algos/blob/main/Classifier%3A%20Types_of_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Cross Validations Techniques
https://www.youtube.com/watch?v=7062skdX05Y

Video help is availble on : https://www.youtube.com/watch?v=3fzYdnuvEfk

In [ ]:
import pandas as pd
df=pd.read_csv('cancer_dataset.csv')   ## https://github.com/gulabpatel/Dataset/blob/main/cancer_dataset.csv
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
###  Independent And dependent features
X=df.iloc[:,2:]
y=df.iloc[:,1]

In [ ]:
X.head()

radius_mean  texture_mean  ...  fractal_dimension_worst  Unnamed: 32
0        17.99         10.38  ...                  0.11890          NaN
1        20.57         17.77  ...                  0.08902          NaN
2        19.69         21.25  ...                  0.08758          NaN
3        11.42         20.38  ...                  0.17300          NaN
4        20.29         14.34  ...                  0.07678          NaN

[5 rows x 31 columns]

In [ ]:
X=X.dropna(axis=1)

In [ ]:
X.head()

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
y.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

### HoldOut Validation Approach- Train And Test Split

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=4)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
result = model.score(X_test, y_test)
print(result)

0.9064327485380117


### K Fold Cross Validation

In [ ]:
from sklearn.model_selection import KFold
model=DecisionTreeClassifier()
kfold_validation=KFold(10)

In [ ]:
import numpy as np
from sklearn.model_selection import cross_val_score
results=cross_val_score(model,X,y,cv=kfold_validation)
print(results)
print(np.mean(results))

[0.89473684 0.9122807  0.9122807  0.94736842 0.89473684 0.98245614
 0.9122807  0.96491228 0.96491228 0.89285714]
0.9278822055137844


### Stratified K-fold Cross Validation

In [ ]:
from sklearn.model_selection import StratifiedKFold
skfold=StratifiedKFold(n_splits=5)
model=DecisionTreeClassifier()
scores=cross_val_score(model,X,y,cv=skfold)
print(scores)
print(np.mean(scores))

[0.90350877 0.92982456 0.92982456 0.95614035 0.89380531]
0.9226207110697098


### Leave One Out Cross Validation(LOOCV)

In [ ]:
from sklearn.model_selection import LeaveOneOut
model=DecisionTreeClassifier()
leave_validation=LeaveOneOut()
results=cross_val_score(model,X,y,cv=leave_validation)

In [ ]:
results

array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [ ]:
print(np.mean(results))

0.9332161687170475


### Repeated Random Test-Train Splits
This technique is a hybrid of traditional train-test splitting and the k-fold cross-validation method. In this technique, we create random splits of the data in the training-test set manner and then repeat the process of splitting and evaluating the algorithm multiple times, just like the cross-validation method.

In [ ]:
from sklearn.model_selection import ShuffleSplit
model=DecisionTreeClassifier()
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
results=cross_val_score(model,X,y,cv=ssplit)

In [ ]:
results

array([0.9122807 , 0.92397661, 0.94736842, 0.90643275, 0.93567251,
       0.92982456, 0.91812865, 0.92982456, 0.9122807 , 0.92982456])

In [ ]:
np.mean(results)

0.9245614035087717

---------------------------------